apiVersion: v1
kind: Service
metadata:
  name: simple-devops-app
  labels:
    app: simple-devops-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
spec:
  type: LoadBalancer
  selector:
    app: simple-devops-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
