apiVersion: v1
kind: Service
metadata:
  name: simple-devops-app
  labels:
    app: simple-devops-app
spec:
  type: ClusterIP
  selector:
    app: simple-devops-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
